### ISSUE TITLE
Can't override style with className or JSS in a clean way

### ISSUE THREAD

**Issue by ryancrunchi** [couetilc/react-social-icons#100]
I would like to be able to override width and height with css via `className` or other styling library like `styled-components`.

Currently not possible because width and height are set by default in `style` prop which takes precedence over any other style.

Workaround is to override width, height in `style` prop or set css `!important`

**Comment by ryancrunchi** [comment]
Moreover, child elements like `.social-svg` cannot be overridden with style in typescript. See this example :

```javascript
<SocialIcon
  network="facebook"
  style={{
    width: 48,
    height: 48,
    '.social-svg': { // ⚠️ not working because Object literal may only specify known properties, and ''.social-svg'' does not exist in type 'Properties<string | number, string & {}>'
      borderRadius: 10,
    },
  }}
/>
```

What would be really clean is to be able to override any style of the icon and its children with className like :

```javascript
// customize SocialIcon
const StyledIcon = styled(SocialIcon)({
  width: 48,
  height: 48,
  '.social-svg': {
    borderRadius: 10,
  },
})

// use it
<StyledIcon network="facebook" />
```

For this to work, the default styles should be applied with css and class selectors, not with style prop as in https://github.com/jaketrent/react-social-icons/blob/ed0876adfadcd770d82aa11e2baee04dbb7048d4/src/social-icon.js#L31

**Comment by couetilc** [comment]
hi @ryancrunchi, `!important` is the way to go to override any of the CSS styles on child elements. You can also set width and height explicitly through the style prop, there's an example here: https://react-social-icons.com/. This library does not support nested CSS declarations AKA css-in-js object syntax.
