### ISSUE TITLE
Minor graphic issue with Tik Tok Logo

### ISSUE THREAD

**Issue by SaileshKumar** [couetilc/react-social-icons#101]
Hi! I think there might be a border issue on the Tik Tok logo. My app is setup to not show the border and only show the "icon" itself, but you still see a border just on Tik Tok.

I'm basically passing in white for bgColor and black for fgColor:

![Screen Shot 2021-11-16 at 1 40 37 PM](https://user-images.githubusercontent.com/5958218/142046328-7f57e381-531a-4a4c-92d0-02477073fbac.png)

**Comment by pbozyk** [comment]
Still the same

**Comment by couetilc** [comment]
hi @SaileshKumar , this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)
