### ISSUE TITLE
Graphical Issues with Discord Icon

### ISSUE THREAD

**Issue by advra** [couetilc/react-social-icons#117]
I found couple issues with discord icon:
- cant set bgColor to transparent (only displays as white)
- discord icon masking is off and shows a circle when colors are changed

To reproduce: 
Note: using twitter icon to show desired result
```
 <SocialIcon network='twitter' bgColor='transparent' fgColor='white'/> 
 <SocialIcon network='discord' fgColor='white' bgColor='black'/>
 <SocialIcon network='discord' fgColor='white' bgColor='transparent'/>
```
Output in order:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1753803/161409092-7045137d-0bed-4bbd-a0b2-d0d10bf18f7b.png">

**Comment by bonbonio** [comment]
I also experience this issue.

**Comment by olliglorioso** [comment]
Probably have to remake the discord icon. I consider doing this tmrw

**Comment by mortslhawmit** [comment]
i also ran in to this when using the transparent as bgColor, fgColor works fine.

**Comment by jefezebos** [comment]
identical issue here.  Is this being looked into? thanks

**Comment by couetilc** [comment]
hi @advra, this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)

CC @bonbonio @mortslhawmit @jefezebos

**Comment by advra** [comment]
@couetilc great work! Thanks!
