### ISSUE TITLE
Tiktok icon is not showing

### ISSUE THREAD

**Issue by brunogdz** [couetilc/react-social-icons#138]
Tiktok icon is not showing, if I try to use the network doesn't work in the same way if I just use the url.

Someone is having that issue too?

version: "react-social-icons": "^5.15.0"

**Comment by simplayy** [comment]
did you check the color? 
I remind you that the color of the logo is black

**Comment by couetilc** [comment]
Please try [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons).
