### ISSUE TITLE
Request: Add skype, castbox, viber and gitlab icon

### ISSUE THREAD

**Issue by nafasebra** [couetilc/react-social-icons#139]
I have a request
it's would be better if include the media icon

the links:
- https://castbox.fm/
- https://www.viber.com/
- https://www.skype.com/en/
- https://about.gitlab.com/

**Comment by couetilc** [comment]
@nafasebra Please refer to [CONTRIBUTING.md](https://github.com/couetilc/react-social-icons/blob/main/CONTRIBUTING.md) for instructions for how contribute an icon to this library.
