### ISSUE TITLE
Request: UberEats & Doordash

### ISSUE THREAD

**Issue by soundsystems** [couetilc/react-social-icons#140]
Can you please add these two delivery icons? Would help a lot. I am having issues with using @svgr/webpack in my Next13 project, but your library is working perfectly.

**Comment by couetilc** [comment]
@soundsystems Please refer to [CONTRIBUTING.md](https://github.com/couetilc/react-social-icons/blob/main/CONTRIBUTING.md) for instructions for how contribute an icon to this library.
