### ISSUE TITLE
Discord Icon is not working

### ISSUE THREAD

**Issue by ahernandezwitSound** [couetilc/react-social-icons#141]
Hi! Im tying to use the discord logo with the following code: 

`<SocialIcon network="discord" fgColor="gray" bgColor="transparent" />`

and is showing something like this: 

![image](https://user-images.githubusercontent.com/108516819/198897771-e7d028d2-e23e-40be-bb46-33a0a2bcad6d.png)

Any suggestions?

Thank you for ur work!

**Comment by SuperNova-94** [comment]
I'm getting the same

**Comment by couetilc** [comment]
hi @ahernandezwitSound, this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)

CC @SuperNova-94
