### ISSUE TITLE
bgColor='transparent' doesn't work properly on discord icon

### ISSUE THREAD

**Issue by john-basilio** [couetilc/react-social-icons#151]
I'm using the latest version of react-social-icons by the time of writing this.

I encountered an issue where when you use bgColor='transparent' on discord, it just makes the background copy the fgColor

Notes:

>So far, I've only encountered this issue when using discord icon.

>I tried using a hex and rgba with 0 opacity/transparency but its still the same as it copies the fgColor

>As I said, when bgColor is set to transparent. It won't really be transparent but instead change to the color that you put in fgColor.

**Comment by rjpeart** [comment]
Also noticed this problem today. think this icon may have two backgrounds, one of which is set to white fill which can't be changed.

**Comment by Jonak-Adipta-Kalita** [comment]
I noticed it aswell, when I was working on my Portfolio....

**Comment by couetilc** [comment]
hi @john-basilio , this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)

CC @rjpeart @Jonak-Adipta-Kalita
