### ISSUE TITLE
Problem with the tiktok icon

### ISSUE THREAD

**Issue by thomaslprr** [couetilc/react-social-icons#155]
## Issue
The TikTok icon is not correctly defined (see screenshot). Borders of the icon are not sharp.

![image](https://user-images.githubusercontent.com/49031473/214125757-ac8d46e9-741e-453a-8967-ababe23e0acd.png)

## Code:
``` <SocialIcon url="https://www.tiktok.com/@xxxxxx" fgColor='white'/> ```

## Configuration: 
OS : MacOs Monterey 
React version : 17.0.2
React social icons version :  5.15.0

**Comment by Grzechu335** [comment]
I have the same issue.

**Comment by lizzieshipwreck** [comment]
Same. It makes this package literally unusable for me. Looks like there is a PR open to fix it here: https://github.com/jaketrent/react-social-icons/issues/146 but no one has merged it yet

**Comment by couetilc** [comment]
hi @thomaslprr this has been addressed in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons)

CC @Grzechu335
