### ISSUE TITLE
Accessibility issue with aria attributes

### ISSUE THREAD

**Issue by farcondee** [couetilc/react-social-icons#164]
Google's PageSpeed Insights tool (or Lighthouse in Chrome) reports Accessibility issues with this package. Using this library very negatively affected my accessiblity score. Check screenshot:

![Screenshot 2023-06-30 at 23 30 20](https://github.com/jaketrent/react-social-icons/assets/75057043/477c1718-6d3e-477f-a0de-39ce8f139d89)

**Comment by couetilc** [comment]
@farcondee you have not specified a URL or HREF for the underlying anchor element, hence the role becomes "generic" for which aria-label is not valid (see https://www.w3.org/TR/wai-aria-1.2/#aria-label). If you want to use the icons as an image without linking to anything, please add a `role="img"` as a prop on the component, and google will correctly identify aria-label as a valid attribute on the element. 

For example:
```js
<SocialIcon network="twitter" role="img" />
```
and
```js
<SocialIcon network="pinterest" role="img" />
```
