### ISSUE TITLE
X.com icon used for any domain that has `x` in it

### ISSUE THREAD

**Issue by orels1** [couetilc/react-social-icons#191]
Hey! Just wanted to say thanks for keeping this library maintained all this time, it's been very helpful over the years 🙏 

## What is happening

With the recent v6 release and addition of the `x.com` support - any domain that has `x` in it is now treated as `x.com`.

E.g. if you use `https://tlx.dev` it will be marked with x.com's icon and not with a generic link icon.

I looked at the code and it seems like the issue comes primarily from the fact that the generator doesn't utilize tlds in the search, so it results in a regex like this being constructed

```
(?:https?:\/\/(?:[a-z0-9-])?)?(x)[.]
```

Which would match anything with an x

![image](https://github.com/couetilc/react-social-icons/assets/3798928/ae28aa23-0d10-4be1-bcf8-e94749a3c5ad)

## What is the desired result

It feels like the matcher should also include the tld so then it will not grab unrelated websites like that.

**Comment by couetilc** [comment]
@orels1 Thank you for the kind words. The issue has been addressed in [v6.4.0](https://github.com/couetilc/react-social-icons/releases/tag/v6.4.0)
