### ISSUE TITLE
Threads Icon

### ISSUE THREAD

**Issue by Aerilym** [couetilc/react-social-icons#227]
I was surprised to find the [Threads](threads.net) icon missing from the library. 

If nobody is working on adding it I'll see about adding it.

**Comment by couetilc** [comment]
Hi @Aerilym, `react-social-icons` is open to contributions, please read [CONTRIBUTING.md](https://github.com/couetilc/react-social-icons/blob/main/CONTRIBUTING.md) for instructions on adding a new icon. I am looking forward to your contribution.

**Comment by jessupjn** [comment]
https://github.com/couetilc/react-social-icons/pull/292

**Comment by couetilc** [comment]
@jessupjn released in v6.12.0. Thank you for contributing.

cc @Aerilym
