### ISSUE TITLE
Added Patreon icon but missing permissions

### ISSUE THREAD

**Issue by DSD3V** [couetilc/react-social-icons#271]
I worked on adding the Patreon icon, but when I go to publish my branch and create a PR, I receive the following error:

You don't have permissions to push to "couetilc/react-social-icons" on GitHub. Would you like to create a fork and push to it instead?

Could I either be granted permissions, or could someone with permissions add the icon? Steps are:

1. Update `package.json` to include `"./patreon": "./dist/icons/patreon.js",`
2. Create `patreon.json` file in the `db` folder with the following contents:
```
{
  "color": "#000000",
  "path": "M 52.8531 23.4586 C 52.8449 17.7383 48.3906 13.0488 43.1625 11.359 C 36.6711 9.259 28.1098 9.5625 21.9109 12.4855 C 14.3996 16.032 12.0398 23.7977 11.9523 31.5414 C 11.8812 37.9098 12.5156 54.6797 21.9738 54.8 C 29.0039 54.8875 30.0512 45.8312 33.3023 41.4699 c 2.3133 -3.1035 5.2937 -3.9785 8.9605 -4.8863 c 6.3027 -1.5613 10.5984 -6.5352 10.5902 -13.125 z m 0 0"
}

```

Here are screenshots showing resulting changes, and unit tests passed:

<img width="500" alt="Screenshot 2024-01-18 at 2 55 44 PM" src="https://github.com/couetilc/react-social-icons/assets/60281799/bab4deb9-3472-4036-85e2-bc4053970647">
<img width="500" alt="Screenshot 2024-01-18 at 3 24 11 PM" src="https://github.com/couetilc/react-social-icons/assets/60281799/b95f1b17-667a-4335-873c-1e51f8ae2dcf">
<img width="816" alt="Screenshot 2024-01-18 at 3 25 16 PM" src="https://github.com/couetilc/react-social-icons/assets/60281799/14ac429c-1048-4838-82b3-28996dd6ed10">

**Comment by couetilc** [comment]
Hi @DSD3V , to create a PR, fork this repo, apply your changes, and then open a PR against this repo with your new commits. 

Take a look at GitHub's documentation outlining their workflow in this regard https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

Thank you for contributing.

**Comment by DSD3V** [comment]
[PR here](https://github.com/couetilc/react-social-icons/pull/272)
