### ISSUE TITLE
Requesting new Twitter (X) icon

### ISSUE THREAD

**Issue by MarcGodard** [couetilc/react-social-icons#366]
Requesting new Twitter (X) icon

**Comment by couetilc** [comment]
@MarcGodard why?

**Comment by MarcGodard** [comment]
I mean the lable still says twitter, didnt check the icon yet. Should the label change to x or add a spacial multiple case?

**Comment by couetilc** [comment]
@MarcGodard your concern is valid. Recognize twitter.com continues to be a valid domain for x.com. Examining the codebase reveals two db entries, x.json and twitter.json, one with the old twitter and one for the new x icon. For continuity's sake, we will continue to maintain the old twitter icon associated with the old domain. Those wishing for the X icon should change twitter links to X links. 

Marc, take time to describe your perspective when opening issues, and a short effort personally exploring a solution goes a long way.
