### ISSUE TITLE
Import a single icon?

### ISSUE THREAD

**Issue by gpmcadam** [couetilc/react-social-icons#67]
Is there a way to import only the icon(s) you are using, rather than the whole set, to keep the final bundle size lower?

Thanks!

**Comment by couetilc** [comment]
hi @gpmcadam, code-splitting has been implemented in [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons). [Check out the README for instructions](https://github.com/couetilc/react-social-icons) on how to take advantage of it in your own project.
